Repository DCI-fbw11/bookmark-api, pull requests merged in 2019-05, with the labels that each got.

#57 Refactor/bookmarkapi 31 getrequestformongoose
  controller/bookmark.js
  helpers/errorMessages.js
Labels: WIP, refactoring

#68 Feature/bookmarkapi 55
  controller/bookmark.js
  middleware/api.js
  routes/api.js
Labels: enhancement

#174 Prod is broken WIP
  app.js
  config/config.js
  db/connection.js
  now.json
  package-lock.json
  package.json
Labels: WIP
